// <auto-generated />
using DietProyect_IV.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietProyect_IV.Migrations
{
    [DbContext(typeof(DietProyect_IVContext))]
    partial class DietProyect_IVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DietProyect_IV.Models.CalculoCalorias", b =>
                {
                    b.Property<int>("CalculoCaloriasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalculoCaloriasId"));

                    b.Property<double>("CaloriasDiarias")
                        .HasColumnType("float");

                    b.Property<int>("NivelActividadId")
                        .HasColumnType("int");

                    b.Property<double>("TasaMetabolicaBasal")
                        .HasColumnType("float");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CalculoCaloriasId");

                    b.HasIndex("NivelActividadId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CalculoCalorias");
                });

            modelBuilder.Entity("DietProyect_IV.Models.NivelActividad", b =>
                {
                    b.Property<int>("NivelActividadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NivelActividadId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("FactorActividad")
                        .HasColumnType("float");

                    b.HasKey("NivelActividadId");

                    b.ToTable("NivelActividades");
                });

            modelBuilder.Entity("DietProyect_IV.Models.ObjetivoCalorico", b =>
                {
                    b.Property<int>("ObjetivoCaloricoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjetivoCaloricoId"));

                    b.Property<int>("AjusteCalorias")
                        .HasColumnType("int");

                    b.Property<int>("CalculoCaloriasId")
                        .HasColumnType("int");

                    b.Property<string>("TipoObjetivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ObjetivoCaloricoId");

                    b.HasIndex("CalculoCaloriasId");

                    b.ToTable("ObjetivosCaloricos");
                });

            modelBuilder.Entity("DietProyect_IV.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<double>("AlturaCm")
                        .HasColumnType("float");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PesoKg")
                        .HasColumnType("float");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DietProyect_IV.Models.CalculoCalorias", b =>
                {
                    b.HasOne("DietProyect_IV.Models.NivelActividad", "NivelActividad")
                        .WithMany()
                        .HasForeignKey("NivelActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietProyect_IV.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelActividad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DietProyect_IV.Models.ObjetivoCalorico", b =>
                {
                    b.HasOne("DietProyect_IV.Models.CalculoCalorias", "CalculoCalorias")
                        .WithMany()
                        .HasForeignKey("CalculoCaloriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculoCalorias");
                });
#pragma warning restore 612, 618
        }
    }
}
